[package]
name = "succinct-block-encoding-length"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[dependencies]
ere-platform-sp1.workspace = true
block-encoding-length-guest = { workspace = true, features = ["std"] }
