[package]
name = "benchmark-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
witness-generator.workspace = true
zkevm-metrics.workspace = true
ere-zkvm-interface.workspace = true

guest-libs = { workspace = true, default-features = true }

reth-guest-io.workspace = true
block-encoding-length-io.workspace = true

ere-dockerized.workspace = true
ere-io-serde.workspace = true

alloy-rlp.workspace = true
alloy-eips.workspace = true
alloy-genesis.workspace = true

reth-stateless.workspace = true

ethrex-guest-program.workspace = true
ethrex-common.workspace = true
ethrex-rlp.workspace = true
ethrex-rpc.workspace = true

rayon.workspace = true
tracing.workspace = true
walkdir.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
rkyv.workspace = true
bincode.workspace = true
strum.workspace = true
anyhow = "*"

[lints]
workspace = true
