[package]
name = "zisk-panic-guest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ere-platform-zisk.workspace = true

[lints]
workspace = true
