[package]
name = "openvm-empty-program"
version = "0.1.0"
edition = "2021"
rust-version = "1.86"
license = "MIT OR Apache-2.0"

[dependencies]
openvm = { workspace = true, features = ["std"] }
openvm-algebra-guest.workspace = true
openvm-ecc-guest.workspace = true
