[package]
name = "reth-risc0-stateless-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
reth-guest = { workspace = true, default-features = true }
ere-platform-risc0 = { workspace = true, features = ["std", "unstable", "getrandom", "sys-getenv"] }
guest-libs.workspace = true
sha2.workspace = true

reth-stateless.workspace = true
reth-ethereum-primitives = { workspace = true, features = [
    "serde",
    "serde-bincode-compat",
] }
reth-primitives-traits = { workspace = true, features = [
    "serde",
    "serde-bincode-compat",
] }

revm = { workspace = true, features = ["std", "c-kzg", "blst", "bn"] }

alloy-primitives = { workspace = true, default-features = false, features = [
    "map-foldhash",
    "serde",
    "tiny-keccak",
] }

k256.workspace = true
