[package]
name = "reth-pico-stateless-validator"
version = "0.1.0"
edition = "2024"

[dependencies]
ere-platform-pico.workspace = true
reth-guest = { workspace = true, default-features = true }
guest-libs.workspace = true
sha2.workspace = true

reth-stateless.workspace = true
reth-ethereum-primitives = { workspace = true, features = [
    "serde",
    "serde-bincode-compat",
] }
reth-primitives-traits = { workspace = true, features = [
    "serde",
    "serde-bincode-compat",
] }

revm = { workspace = true, default-features = false, features = ["bn"] }
alloy-primitives = { workspace = true, default-features = false, features = [
    "map-foldhash",
    "serde",
    "sha3-keccak",
] }
k256.workspace = true

kzg-rs = { git = "https://github.com/brevis-network/kzg-rs", rev = "b93499a67494bc6d34e108032fd11d375fb886e0" }
