[package]
name = "reth-guest-io"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
guest-libs.workspace = true
ere-io-serde.workspace = true

reth-stateless.workspace = true
reth-ethereum-primitives.workspace = true
reth-primitives-traits.workspace = true
alloy-consensus.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_with.workspace = true
anyhow.workspace = true
