[package]
name = "reth-guest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
guest-libs.workspace = true
sparsestate.workspace = true
reth-guest-io.workspace = true
ere-io-serde.workspace = true

# reth
reth-primitives-traits.workspace = true
reth-ethereum-primitives = { workspace = true, features = [
    "serde",
    "serde-bincode-compat",
] }
reth-chainspec.workspace = true
reth-stateless.workspace = true
reth-evm-ethereum.workspace = true
reth-trie-common.workspace = true

# alloy
alloy-primitives.workspace = true

# external
k256.workspace = true
bincode_v2.workspace = true
serde.workspace = true
serde_with.workspace = true
once_cell.workspace = true

[features]
default = ["std", "reth-stateless/default"]
std = ["guest-libs/std", "once_cell/std"]
