[package]
name = "reth-airbender-stateless-validator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ere-platform-airbender = { workspace = true, features = ["custom_allocator"] }
reth-guest.workspace = true
guest-libs.workspace = true

reth-stateless = { workspace = true, features = ["k256"] }
reth-ethereum-primitives = { workspace = true, features = [
    "serde",
    "serde-bincode-compat",
] }
reth-primitives-traits = { workspace = true, features = [
    "serde",
    "serde-bincode-compat",
] }

revm = { workspace = true, default-features = false, features = ["bn"] }
alloy-primitives = { workspace = true, default-features = false, features = [
    "map-foldhash",
    "serde",
    "sha3-keccak",
] }
k256.workspace = true
sha2.workspace = true
